/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-09-06 04:55:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.moana;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class moana_005f3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Moana</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"moana.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("            table {\r\n");
      out.write("           width: 100%;\r\n");
      out.write("           border-top: 1px solid #444444;\r\n");
      out.write("           border-collapse: collapse;\r\n");
      out.write("         }\r\n");
      out.write("         th, td {\r\n");
      out.write("           border-bottom: 1px solid #444444;\r\n");
      out.write("           padding: 10px;\r\n");
      out.write("         }\r\n");
      out.write("       a.jcm-top {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    right: 15px;\r\n");
      out.write("    bottom: 15px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    background-color:white;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("           </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"#\" class=\"jcm-top hidden-xs hidden-sm\"><img src = \"../christmas_img/goto.png\" width=\"50px\" height=\"50px\"></a>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$( document ).ready( function() {\r\n");
      out.write("$( window ).scroll( function() {\r\n");
      out.write("if ( $( this ).scrollTop() > 200 ) {\r\n");
      out.write("$( '.jcm-top' ).fadeIn();\r\n");
      out.write("} else {\r\n");
      out.write("$( '.jcm-top' ).fadeOut();\r\n");
      out.write("}\r\n");
      out.write("} );\r\n");
      out.write("$( '.jcm-top' ).click( function() {\r\n");
      out.write("$( 'html, body' ).animate( { scrollTop : 0 }, 400 );\r\n");
      out.write("return false;\r\n");
      out.write("} );\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("  <section class = \"section_menu\">\r\n");
      out.write("                <a href = \"../list.jsp\"> <button>자유게시판</button></a>\r\n");
      out.write("               <article class = \"menu\">\r\n");
      out.write("                <a href = \"../index.jsp\"><p class = \"index\">Index</p></a>\r\n");
      out.write("                            <ul class = \"mylist\">\r\n");
      out.write("                                <li class = \"snow_link\"><a href = \"../snow/snow_1.jsp\" style = \"color:black\"><label>Snow White</label></a></li>\r\n");
      out.write("                                <li class = \"mermaid_link\"><a href = \"../mermaid/mermaid_1.jsp\" style = \"color:black\"><label>The Little Mermaid</label></a></li>\r\n");
      out.write("                                <li class = \"christmas_link\"><a href = \"../christmas/christmas_1.jsp\" style = \"color:black\"><label>The Nightmare before Christmas</label></a></li>\r\n");
      out.write("                                <li class = \"rata_link\"><a href = \"../rata/rata_1.jsp\" style = \"color:black\"><label>Ratatouille</label></a></li>\r\n");
      out.write("                                <li class = \"inside_link\"><a href = \"../inside/inside_1.jsp\" style = \"color:black\"><label>Inside Out</label></a></li>\r\n");
      out.write("                                <li class = \"moana_link\"><a href = \"../moana/moana_1.jsp\" style = \"color:black\"><label>Moana</label></a></li>\r\n");
      out.write("                                <li class = \"koko_link\"><a href = \"../koko/koko_1.jsp\" style = \"color:black\"><label>Coco</label></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </article>\r\n");
      out.write("        \r\n");
      out.write("               \r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section class = \"section_content\">\r\n");
      out.write("               <article>\r\n");
      out.write("                    <table border=\"0\" width = \"90%\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style = \"text-align: center;\">\r\n");
      out.write("                                <h1>명대사</h1>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                \"그러나 당신을 마우이로 만든 건 신들이 아니예요, 바로 당신 자신이죠\" \r\n");
      out.write("                                <br>But the gods aren't the ones who make you Maui You are<br><br>\r\n");
      out.write("                                \"당신도 우리와 함께 가도 돼요. 우리 마을 사람들에게는 능숙한 항해사가 필요하거든요\"<br>\r\n");
      out.write("                                \"네 마을 사람들에게는 항해사가 이미 한 명 있어\"<br>\r\n");
      out.write("                                You could come with us you know. My people are goinh to need a master wayfinder.<br>\r\n");
      out.write("                                They already have one.<br><br>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <!-- https://blog.naver.com/PostView.nhn?blogId=cine_play&logNo=220958817529&parentCategoryNo=&categoryNo=6&viewDate=&isShowPopularPosts=false&from=postView -->\r\n");
      out.write("                            <td style = \"padding:3%;\">\r\n");
      out.write("                                    <label style = \"text-align: center\"><h1>줄거리</h1></label>  \r\n");
      out.write("                                    <img src = \"../moana_img/mmoo.png\" width=\"40%\" height=\"100%\" align=\"left\" style = \"margin-right: 2%;\">\r\n");
      out.write("                                    모든 것이 완벽했던 모투누이 섬이 저주에 걸리자바다가 선택한 소녀 모아나는 섬을 구하기 위해 머나먼 항해를 떠난다.\r\n");
      out.write("                                    저주를 풀기 위해서는 오직 신이 선택한 전설의 영웅 마우이의 힘이 필요한 상황! 모아나는 마우이를 우여곡절 끝 설득해, \r\n");
      out.write("                                    운명적 모험을 함께 떠나는데… 바다가 부르면 운명적 모험이 시작된다!\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <!-- http://extmovie.maxmovie.com/xe/movietalk/16739989 -->\r\n");
      out.write("                        <td style = \"text-align: center; padding:3%\">\r\n");
      out.write("                            <h1>이스터에그</h1>\r\n");
      out.write("                            혹시 이 장면을 아시나요?<br><br>\r\n");
      out.write("                            <img src = \"../moana_img/eeeeeeee.PNG\" width=\"90%\" height=\"70%\"><br><br>\r\n");
      out.write("                            이 장면 속에서 무언가 이상한 점을 못 느끼셨나요?<br>\r\n");
      out.write("                            그럼 이 캐릭터를 보여드리죠!<br><br>\r\n");
      out.write("                            <img src = \"../moana_img/big.png\" width=\"30%\" height=\"90%\"><br><br>\r\n");
      out.write("                            이제 조금 아시겠나요?<br><br>\r\n");
      out.write("                            <img src = \"../moana_img/e2.PNG\"><br><br>\r\n");
      out.write("                            모아나가 닭인 헤이헤이를 구출하기 위해 바다 해적들에게로 뛰어 드는 장면입니다. <br>\r\n");
      out.write("                            이 장면에서 디즈니의 또 다른 영화 '빅 히어로'의 주인공이 나왔습니다.\r\n");
      out.write("                           \r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </table>\r\n");
      out.write("               </article>\r\n");
      out.write("               <a href = \"moana_4.jsp\"><article class = \"next_page\"><label style=\"font-weight: 800\">OST</label><img src = \"../snow_img/nn.png\"></article></a>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            <footer>Copyright&copy;2018 3517 최민경 All rights reserved. </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
