/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-09-05 04:03:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Disney</title>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- top 으로 올라가는 버튼 만들기!! -->\r\n");
      out.write("<style>\r\n");
      out.write("        html, body{\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            padding:0;\r\n");
      out.write("            margin:0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     article\r\n");
      out.write("     {\r\n");
      out.write("         display: inline;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     img\r\n");
      out.write("     {\r\n");
      out.write("         display: inline;\r\n");
      out.write("         position: relative;\r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     .mermaid\r\n");
      out.write("     {\r\n");
      out.write("        margin-left:10%;\r\n");
      out.write("        width:15.5%;\r\n");
      out.write("        height:20.5%;\r\n");
      out.write("        padding-left: 250px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .snowwhite{\r\n");
      out.write("        width:16.5%;\r\n");
      out.write("        height:20.5%;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .pocahontas{\r\n");
      out.write("        float: right;\r\n");
      out.write("        height:33%;\r\n");
      out.write("        width:21%;\r\n");
      out.write("        padding-right:450px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .rata{\r\n");
      out.write("         height: 30%;\r\n");
      out.write("         width:23.3%;\r\n");
      out.write("         padding-left: 443px;\r\n");
      out.write("    } \r\n");
      out.write("    \r\n");
      out.write("    .dd{\r\n");
      out.write("        height:12%;\r\n");
      out.write("        width:8.5%;\r\n");
      out.write("        float: right;\r\n");
      out.write("       margin-right:6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .frozen{\r\n");
      out.write("        height:150px;\r\n");
      out.write("        width:130px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .inside{\r\n");
      out.write("        height: 17.5%;\r\n");
      out.write("        width: 13%;\r\n");
      out.write("        float: right;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        margin-top:6.4%;\r\n");
      out.write("        margin-left:0.3%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .moana{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        height: 17.6%;\r\n");
      out.write("        width: 16.4%;\r\n");
      out.write("        margin-left:13.7%;\r\n");
      out.write("        margin-top:6.4%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- https://youtu.be/4-o6y5VPXkM -->\r\n");
      out.write("    \r\n");
      out.write("    <embed src=\"image/Walt Disney Opening Video(월트 디즈니 오프닝 영상) (1).mp3\" autostart=\"true\" hidden=\"true\" loop=\"false\">\r\n");
      out.write("    <center>\r\n");
      out.write("        <header>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <img src=\"image/desney1.png\" height=\"150\" width=\"350\">\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("    </center>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("            <a href = \"mermaid/mermaid_1.jsp\"><img src = \"image/mermaid.png\" class = \"mermaid\"></a>\r\n");
      out.write("            <a href = \"snow/snow_1.jsp\"><img src = \"image/snowwhite1.png\" class = \"snowwhite\"></a>\r\n");
      out.write("            <a href = \"christmas/christmas_1.jsp\"><img src = \"image/chis.jpg\" class = \"pocahontas\"></a>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("            <a href = \"rata/rata_1.jsp\"><img src = \"image/rata2.png\" class = \"rata\"></a>\r\n");
      out.write("            <a href = \"index.jsp\"><img src = \"image/dd.jpg\" class = \"dd\"></a>\r\n");
      out.write("     </article>\r\n");
      out.write("     \r\n");
      out.write("     <article>\r\n");
      out.write("         <a href = \"inside/inside_1.jsp\"><img src = \"image/Insideout.png\"class = \"inside\"></a>\r\n");
      out.write("         <a href = \"moana/moana_1.jsp\"><img src = \"image/moaaa.jpg\" class = \"moana\"></a>\r\n");
      out.write("     </article>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
