/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-09-05 01:19:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.christmas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class christmas_005f4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>The Nightmare before Christmas</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"christmas.css\">\r\n");
      out.write("<style>\r\n");
      out.write("      .song:hover{\r\n");
      out.write("          color: orangered;\r\n");
      out.write("          font-weight: 800;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <section class = \"section_menu\">\r\n");
      out.write("                <a href = \"../list.jsp\"> <button>자유게시판</button></a>\r\n");
      out.write("               <article class = \"menu\">\r\n");
      out.write("                <a href = \"../index.jsp\"><p class = \"index\">Index</p></a>\r\n");
      out.write("                            <ul class = \"mylist\">\r\n");
      out.write("                                <li class = \"snow_link\"><a href = \"../snow/snow_1.jsp\" style = \"color:black\"><label>Snow White</label></a></li>\r\n");
      out.write("                                <li class = \"mermaid_link\"><a href = \"../mermaid/mermaid_1.jsp\" style = \"color:black\"><label>The Little Mermaid</label></a></li>\r\n");
      out.write("                                <li class = \"christmas_link\"><a href = \"../christmas/christmas_1.jsp\" style = \"color:black\"><label>The Nightmare before Christmas</label></a></li>\r\n");
      out.write("                                <li class = \"rata_link\"><a href = \"../rata/rata_1.jsp\" style = \"color:black\"><label>Ratatouille</label></a></li>\r\n");
      out.write("                                <li class = \"inside_link\"><a href = \"../inside/inside_1.jsp\" style = \"color:black\"><label>Inside Out</label></a></li>\r\n");
      out.write("                                <li class = \"moana_link\"><a href = \"../moana/moana_1.jsp\" style = \"color:black\"><label>Moana</label></a></li>\r\n");
      out.write("                                <li class = \"koko_link\"><a href = \"../koko/koko_1.jsp\" style = \"color:black\"><label>Coco</label></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </article>\r\n");
      out.write("        \r\n");
      out.write("               \r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section class = \"section_content\">\r\n");
      out.write("                    <!-- https://youtu.be/tLqITu3yJEA -->\r\n");
      out.write("               <article>     \r\n");
      out.write("                    <a href=\"../christmas_img/[한글자막] This is Halloween - 크리스마스의 악몽 This is Halloween - The Nightmare before Christmas (1993).mp4\">\r\n");
      out.write("                        <img src=\"../christmas_img/mimi.jpg\" width=\"30%\" height=\"40%\" align=\"left\">\r\n");
      out.write("                   </a>\r\n");
      out.write("                <a href = \"https://youtu.be/tLqITu3yJEA\" class = \"song\"><label style = \"margin: 2%; font-size:20pt\">This is Halloween</label></a>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                &nbsp; &nbsp;\"This is Halloween, this is Halloween Pumpkins scream in the dead of night\" <br>\r\n");
      out.write("                &nbsp; &nbsp;&nbsp; 지금은 할로윈, 지금은 할로윈 호박들은 깊은 밤 비명을 지르네\r\n");
      out.write("                \r\n");
      out.write("               </article>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- https://youtu.be/8tGflVGrTp8 -->\r\n");
      out.write("            <section  class = \"section_content\" style = \"margin-top: 1%\">\r\n");
      out.write("                  <article>\r\n");
      out.write("                        <a href=\"../christmas_img/[한글자막] Whats this  - 크리스마스의 악몽 Whats this  - The Nightmare before Christmas (1993).mp4\">\r\n");
      out.write("                            <img src=\"../christmas_img/ww.jpg\" width=\"30%\" height=\"20%\" align=\"left\">\r\n");
      out.write("                       </a>\r\n");
      out.write("                      <a href = \"https://youtu.be/8tGflVGrTp8\"  class = \"song\"><label style = \"margin: 2%; font-size:20pt\">What's this</label></a>\r\n");
      out.write("                      <br><br>\r\n");
      out.write("                      &nbsp; &nbsp;\"What's this? There's white things in the air\"\r\n");
      out.write("                      <br>\r\n");
      out.write("                      &nbsp; &nbsp;&nbsp;공중에 하얀 것이 있어 이건 뭐지?\r\n");
      out.write("                  </article>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- https://youtu.be/8rivTGBzBMM -->\r\n");
      out.write("            <section  class = \"section_content\" style = \"margin-top: 1%\">\r\n");
      out.write("                    <article>\r\n");
      out.write("                            <a href=\"../christmas_img/The Nightmare Before Christmas - Sallys Song HQ.mp4\">\r\n");
      out.write("                                <img src=\"../christmas_img/ss.jpg\" width=\"30%\" height=\"20%\" align=\"left\">\r\n");
      out.write("                           </a>\r\n");
      out.write("                        <a href = \"https://youtu.be/8rivTGBzBMM\" class = \"song\"><label style = \"margin: 2%; font-size:20pt\">Sally's Song</label></a>\r\n");
      out.write("                        <br><br>\r\n");
      out.write("                        &nbsp; &nbsp;\"And will he see how much he means to me?\"<br>\r\n");
      out.write("                        &nbsp; &nbsp;&nbsp;그리고   그는 그가 나에게 얼마나 중요한지 알까?\r\n");
      out.write("                    </article>\r\n");
      out.write("              </section>\r\n");
      out.write("            \r\n");
      out.write("              <footer>Copyright&copy;2018 3517 최민경 All rights reserved. </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
